# Generated by Django 4.2 on 2023-06-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0002_alter_medicine_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medical_type',
            new_name='medical_typ',
        ),
    ]
